name = "racedays"
compatibility_date = "2025-01-01"

[assets]
directory = "./frontend/dist"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

[build]
command = "cd frontend && npm install && npm run build"
